services:
  cix-alerts-app:
    build: .
    container_name: cix-alerts-container
    ports:
      - "8009:8009"
    volumes:
      - ./data:/app/data
      # Map the input file so you can edit it locally and test immediately
      - ./soc_alert_raw.json:/app/soc_alert_raw.json
      - ./soc_alert_batch.json:/app/soc_alert_batch.json
    env_file:
      - .env
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8009
